#!/bin/bash
banner CmpKitZ80
cd ~/Fuzix-Compiler-Kit
if [ $? -ne 0 ] ; then exit 1 ; fi
sed -i 's/ -lbsd/ #-lbsd/g' Preprocessor/Makefile
if [ $? -ne 0 ] ; then exit 1 ; fi
export PATH=/opt/fcc/bin:$PATH
make Preprocessor cc cc0 \
     cc1.z80 cc1.byte \
     cc2 cc2.z80 \
     copt \
     supportz80
if [ $? -ne 0 ] ; then echo make FUZIX-COMPILER-KIT Z80 failed ; exit 1 ; fi
echo "MAKE Z80 OK"
#make install
CCROOT=/opt/fcc
	mkdir -p $CCROOT/bin && \
	mkdir -p $CCROOT/lib && \
	cp cc $CCROOT/bin/fcc && \
	cp cc.hlp $CCROOT/lib/cc.hlp && \
	cp cc0 $CCROOT/lib && \
	cp Preprocessor/cpp $CCROOT/lib && \
	mkdir -p $CCROOT/lib/z80/ && \
	mkdir -p $CCROOT/lib/z80/include && \
	cp lorderz80 $CCROOT/bin/lorderz80 && \
	cp cc1.z80 $CCROOT/lib && \
	cp cc2.z80 $CCROOT/lib && \
	cp copt $CCROOT/lib && \
	cp rules.z80 $CCROOT/lib && \
	cp supportz80/crt0.o $CCROOT/lib/z80/ && \
	cp supportz80/include/*.h $CCROOT/lib/z80/include/ && \
	cp supportz80/libz80.a $CCROOT/lib/z80/libz80.a && \
	ar cq $CCROOT/lib/z80/libc.a
if [ $? -ne 0 ] ; then echo install FUZIX-COMPILER-KIT failed ; exit 1 ; fi
echo "MAKE INSTALL OK"
banner CmpKitZ80 Successful
