#!/bin/bash
cd ~/Fuzix-Compiler-Kit
if [ $? -ne 0 ] ; then exit 1 ; fi
export PATH=/opt/fcc/bin:$PATH
make bootstuff
if [ $? -ne 0 ] ; then echo make bootstuff failed! ; exit 1 ; fi
make bootinst
if [ $? -ne 0 ] ; then echo make bootinst failed! ; exit 1 ; fi
make all
if [ $? -ne 0 ] ; then echo make all failed! ; exit 1 ; fi
make install
if [ $? -ne 0 ] ; then echo make install failed! ; exit 1 ; fi
echo Successful.
