#!/bin/bash
build() {
/mount/clone_sdcc280 && \
/mount/build_sdcc280-z80 && \
/mount/clone_fuzix-bintools && \
/mount/build_fuzix-bintools && \
/mount/clone_fuzix-compiler-kit && \
/mount/build_fuzix-compiler-kit-bootstrap-z80 && \
/mount/build_fuzix-compiler-kit-z80 && \
/mount/clone_fuzix && \
/mount/build_fuzix-trs80 && \
echo SUCCESSFUL || \
echo FAILED && false
}
start=$(date)
time build
RESULT=$?
echo Started: $start - Finished: $(date) - Result: $RESULT
