#!/bin/sh
cd ~
if [ $? -ne 0 ] ; then exit 1 ; fi
#mkdir -p /mount/FUZIX
if [ $? -ne 0 ] ; then exit 1 ; fi
rsync -r -au --delete --info=progress2 --exclude=.git FUZIX /mount
if [ $? -ne 0 ] ; then exit 1 ; fi
echo Successful.
